name: rasike
favicon: null
layout_spectrum: 0.25043
typography_spectrum: 0.50867
title: RaSiKe cinema seating
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffe8d9'
    - '#00fefb'
    - '#987c6b'
    - '#ff0000'
  brandStrength: 0.125
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
